name: reproducibility
channels:
  - conda-forge
dependencies:
  - constrainmol
  - ele
  - foyer>=0.9.4
  - freud
  - gmso
  - gsd
  - h5py
  - jinja2
  - matplotlib
  - mbuild>=0.13.0
  - mdtraj
  - mosdef_cassandra
  - numpy
  - openmm>=7.6
  - packmol>=18
  - pandas
  - panedr
  - parmed>=3.4.3
  - pymbar
  - python=3.8
  - rdkit
  - scipy
  - signac
  - signac-flow
  - unyt
