name: reproducibility
channels:
  - conda-forge
  - bioconda
dependencies:
  - cassandra=1.2.5
  - constrainmol
  - ele
  - foyer>=0.9.4
  - freud
  - gmso
  - gromacs=2020.6
  - gsd
  - h5py
  - hoomd=*=*gpu*
  - jupyter
  - jinja2
  - lammps
  - matplotlib
  - mbuild>=0.13.0
  - mdtraj
  - mosdef_cassandra
  - numpy
  - openmm>=7.6
  - packmol>=18
  - pandas
  - panedr
  - parmed>=3.4.3
  - pymbar
  - pytest
  - python=3.8
  - rdkit
  - scipy
  - seaborn
  - signac
  - signac-dashboard
  - signac-flow
  - unyt
