name: build

on:
  push:
    tags:
        - "*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: reproducibility

jobs:
  build-and-push-image:
    if: github.repository_owner == 'cmelab'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set env "TAG"
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/cmelab/${{ env.IMAGE_NAME }}:${{ env.TAG }}
